name: Build Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build:
    uses: nint8835/workflows/.github/workflows/docker-build.yaml@main
    with:
      image_name: nint8835/scribe
      tag_rules: |
        type=raw,value=latest,enable={{is_default_branch}}
        type=raw,value={{branch}}-{{sha}}-{{date 'YYYYMMDD-HHmmss' tz='America/St_Johns'}},enable={{is_default_branch}}
